name: Update data.json
run-name: ${{ github.actor }}
on:
  discussion:
    types: [labeled]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  Clone-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSGraphQL, PSParseHTML
      - name: Run Powershell script
        shell: pwsh
        run: . ./scripts/ConvertFrom-GitHubDiscussionToJson.ps1
      - name: Commit new json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git commit -am "Automated json update"
          git push
